### PR TITLE
Added Result merge method

### PR DESCRIPTION
**Pull request by brendanmaguire**
Also:
* `is_ok` and `is_error` use a comparison instead of a match as the comparison is faster
* Fixed a typo

### CODE REVIEW

**Comment by dbrattli** [comment]
Hi, thanks for the PR. Do you have any reference for the merge operator? Who else is using it? I would prefer operators like `orElse` and `orElseWith`, ref: https://demystifyfp.gitbook.io/fstoolkit-errorhandling/fstoolkit.errorhandling/result/orelsefunctions#result.orelsewith

**Comment by brendanmaguire** [comment]
> Hi, thanks for the PR.

Happy to contribute 🙂 

> Do you have any reference for the merge operator? Who else is using it?

There is an `Either#merge` in Scala ([docs](https://www.scala-lang.org/api/3.x/scala/util/Either.html#merge-0)). (Not sure of your familiarity with Scala but `Either` is pretty much the same as `Result`)

> I would prefer operators like `orElse` and `orElseWith`, ref: https://demystifyfp.gitbook.io/fstoolkit-errorhandling/fstoolkit.errorhandling/result/orelsefunctions#result.orelsewith

`merge` is orthogonal to these imo. An example use of merge would be if you get a `Result` from your service layer and want to convert it to a `HTTPResponse` to return from the router layer.

Simple example:
```python
def create(customer_id: str, email: str) -> HTTPResponse:
    service_result: Result[Customer, InvalidEmailAddress] = service.create_customer(customer_id, email)
    response: HTTPResponse = service_result.map(customer_to_response).map_error(invalid_email_to_response).merge()
    return response
```

I think the above code might also benefit from a `Either#bimap` ([Scala cats docs](https://typelevel.org/cats/api/cats/syntax/EitherOps.html#bimap[C,D](fa:A=%3EC,fb:B=%3ED):Either[C,D])) if you would be open to that addition? I tend to use `bimap` and `merge` together quite often in Scala.

```python
def create(customer_id: str, email: str) -> HTTPResponse:
    service_result: Result[Customer, InvalidEmailAddress] = service.create_customer(customer_id, email)
    response: HTTPResponse = service_result.bimap(customer_to_response, invalid_email_to_response).merge()
    return response
```

**Comment by brendanmaguire** [comment]
I've created a PR to add the `or_else*` methods too #226

**Comment by dbrattli** [comment]
Sorry I think I made a merge conflict with your PR. Anyways, I see that `merge` is the same as `default_with(lambda x: x)`

**Review by dbrattli — APPROVED** [review]
Nice, thanks for contributing this

**Comment by brendanmaguire** [comment]
Nice catch on the `default_with`. Pretty succinct now 🙂

**Pull request merged**
